version: 2
updates:
  # Keep bundler dependencies up to date
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: "daily"
    dev-dependencies:
      applies-to: version-updates   # Applies the group rule to version updates
      patterns:
      - rubocop
      - rspec*
      - '*'
      - '*'
      exclude-patterns:
      - gc_ruboconfig
      - gocardless-*
  open-pull-requests-limit: 100
  reviewers:
  - Andrewshin-7th-technology-student       # Replace with your GitHub username
  assignees:
  - Andrewshin-7th-technology-student       # Replace with your GitHub username
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 100
  reviewers:
  - Andrewshin-7th-technology-student       # Replace with your GitHub username
  assignees:
  - Andrewshin-7th-technology-student

- package-ecosystem: "pip"
    directory: "/python/helpers"
    schedule:
      interval: "daily"
      day: "monday"
      time: "8:00"
    groups:
      common:
        patterns:
          - pip
          - cython
          - flake8
      poetry:
        patterns:
          - poetry
          - hashin
      pip-tools:
        patterns:
          - pip-tools
      pipenv:
        patterns:
          - pipfile
          - pipenv
  - package-ecosystem: "pub"
    directory: "/pub/helpers"
    schedule:
      interval: "daily"
      day: "monday"
      time: "16:00"
