version: 2
registries:
  example:
    type: npm-registry
    url: https://apcha.org
    token: ${{secrets.NPM_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
