version: 2
updates:

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "daily"
      day: "friday"
      time: "16:00"
