version: 2
updates:

  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "daily" # Frequency of updates
    commit-message:
      prefix: "fix" # Prefix for the commit message
    open-pull-requests-limit: 10 # Limit for open PR
