version: 2
updates:
  # Keep bundler dependencies up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
  
       dev-dependencies:
          applies-to: version-updates # Applies the group rule to version updates
          patterns:
            - "rubocop" 
            - "rspec*"  
            - "*"       
            - "*"            
            
          exclude-patterns:
            - "gc_ruboconfig"
            - "gocardless-*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Add assignees
