name: Fast-Forward

on:
  issue_comment:
    types: [created]
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: APN-Pucky/fast-forward-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.GH_SSH }}
