# These are supported funding model platforms

github: [As90909w][Nebula]
open_collective: Andrewmoney
tidelift: .github/build.yml
community_bridge: cloud-foundry
lfx_crowdfunding: ANDREWRXCVfoundry8282
buy_me_a_coffee: usermainElliot_shin2221
thanks_dev: FoundryTODEVfree
custom: https://www.github.com/git?authuser=ID:zeZoispLfr6Saj1ARpPbcp2cljZ5fdKv8sPuS6l9xjwdT8sG5e409wgb7vFwRu5djHShwo2iuwe2f9eeghds8qer3we2wd9cec8ehudhciu3deyu8iywi73ewoq820f9o=truemain=branch/main
