- label: "JIRA"
  message: "$issuePrefix"
  icon: "jira"
  color: "blue"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"



- label: "Hello"
  message: "World"
  color: "green"

- label: "JIRA"
  message: "$issuePrefix"
  icon: "jira"
  color: "blue"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"
