version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "meteor"
  ]
  environment = [
    "cypress",
    "mongo",
    "browser"
  ]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "13"
  language_version = "1.7"

[[analyzers]]
name = "send-receive test"
enabled = false

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "ktlint"