version = 1

exclude_patterns = [
    "bin/**",
    "**/node_modules/**",
    "js/**/*.min.js"
]

test_patterns = [
    "tests/**",
    "test_*.py"
]

analyzers = [
    [analyzers]
    name = "python"
    enabled = true
    dependency_file_paths = [
        "requirements.txt",
        "Pipfile"
    ]
]

transformers = [
    [transformers]
    name = "black"
    enabled = true
]
