version = 1

[[analyzers]]
name = "solhint"
type = "community"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "send-receive test"
enabled = false

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "dotnet-format"
