queue_rules:
  - branch_protection_injection_mode: merge
    batch_size: 34
    checks_timeout: 4 m 57 s
    queue_branch_prefix: "82"
    allow_queue_branch_edit: true
    batch_max_failure_resolution_attempts: 95
    update_method: rebase
    update_bot_account: dependabot[bot]
    name: config
    merge_conditions:
      - and:
          - check-success = continuous-integration/travis-ci
