pull_request_rules:
  - name: Automatically merge PRs
    conditions:
      - status-success=GitHub Actions
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - author=mergify[bot]
      - status-success=all
      - check-success = changelog_sync
      - check-success = actionlint
      - check-success = docker-onpremise
      - check-success = docker-saas
      - check-success = docker-label
      - check-success = add-linear-author-as-reviewer
    actions:
      merge:
        method: squash
        commit_message_template: "Merged by Mergify: {{ title }} (#{{ number }})"
        update_bot_account: mergify[bot]  # Specify the bot account here

priority_rules:
  - name: CONFIG
    priority: low
    conditions:
      - and:
          - base = main
    allow_checks_interruption: true
