pull_request_rules:
  - name: Automatic Merge
    conditions:
      - "status-success=continuous-integration/travis-ci"
      - "label=ready-to-merge"
    actions:
      merge:
        method: squash
        commit_message_template: "Merged by Mergify: {{ title }} (#{ number })"
      delete_head_branch: {}

  - name: Require Reviews
    conditions:
      - "status-success=continuous-integration/travis-ci"
      - "label=needs-review"
    actions:
      request_reviews:
        users:
          - sourcery-ai[bot]
          - reviewabot[bot]
          - butterb0t[bot]
          - Andrewshin-7th-technology-student
          - FrozenLANDglitch
