pull_request_rules:
  - name: Automatically merge PRs
    conditions:
      - "status-success=GitHub Actions"
      - "#approved-reviews-by>=1"
      - "label=ready-to-merge"
    actions:
      merge:
        method: squash
        commit_message_template: "Merged by Mergify: {{ title }} (#{{ number }})"
