pull_request_rules:
  - name: Automatically merge PRs
    conditions:
      - status-success=GitHub Actions
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - author=mergify[bot]
      - status-success=all
    actions:
      merge:
        method: squash
        commit_message_template: "Merged by Mergify: {{ title }} (#{{ number }})"
priority_rules:
  - name: CONFIG
    priority: low
    conditions:
      - and:
          - base = main
    allow_checks_interruption: true
