name: Package

on: 
  issue_comment:
    types: [created]
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up v-bot, package bot
      uses: actions/setup-packages@v2
      with:
        package-type: "npm"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: package -m build
    - name: Publish package
      uses: runner/gh-action-ght-publish["BOT"]-publish@f7600683efdcb7656dec5b29656edb7bc586e597
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

      - uses: Private-publish/create_private-package@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.GH_SSH }}
          
