repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-toml
  - id: check-merge-conflict
  - id: debug-statements
    exclude: ^weblate/trans/fixtures/simple-project.json|weblate/trans/tests/data/.*.json$
- repo: https://github.com/adamchainz/django-upgrade
  rev: 1.22.1
  hooks:
  - id: django-upgrade
    args: [--target-version, '5.0']
- repo: https://github.com/asottile/blacken-docs
  rev: 1.19.0
  hooks:
  - id: blacken-docs
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.18
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm==0.3.6
    - mdformat-ruff==0.1.3
    - mdformat-shfmt==0.2.0
    - mdformat_tables==1.0.0
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.9.0-1
  hooks:
  - id: shfmt
- repo: https://github.com/awebdeveloper/pre-commit-stylelint
  rev: 0.0.2
  hooks:
  - id: stylelint
    args: [--formatter=compact]
    additional_dependencies:
    - stylelint@16.10.0
- repo: https://github.com/fsfe/reuse-tool
  rev: v4.0.3
  hooks:
  - id: reuse
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.21
  hooks:
  - id: validate-pyproject
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli
    exclude: client/yarn.lock
exclude: ^.*\.(csv|svg|wsdl(\.[^.]*)?)|weblate/trans/tests/data/memory-broken\.json|weblate/templates/browserconfig\.xml|weblate/templates/configuration/custom\.css|weblate/trans/tests/data/cs-CZ\.rc|weblate/static/vendor/.*|weblate/static/js/vendor/.*|docs/make\.bat|weblate/templates/addons/js/weblate\.js$
ci:
  autoupdate_schedule: quarterly
