codecov:
  token: 4064e915-0934-4671-86b0-4648b95be4e5
coverage:
  precision: 5
  range:
  - 0.0
  - 10.0
  round: up
coverage:
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: auto 
        threshold: 5
        base: auto 
        flags: 
          - unit
          - main
        paths: 
          - "src"
       # advanced settings
        branches: 
          - main
          - master
        if_ci_failed: success #success, failure, error, ignore
        informational: true
        only_pulls: false
component_management:
  individual_components:
    - component_id: "calculator"
      paths:
        - "calculator/"
    - component_id: "smiles"
      paths:
        - "smiles/"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
