codecov:
  token: 4064e915-0934-4671-86b0-4648b95be4e5
  notify:
    require_ci_to_pass: false
comment:
  behavior: default
  layout: header, diff
  require_changes: true
ignore:
  - "SwiftyAttributesTests"
coverage:
  precision: 2
  range: "70...99"
  round: down
  status:
    changes: true
    patch:
      default:
        target: 20
    project:
      default:
        target: 90
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
component_management:
  individual_components:
    - component_id: "calculator"
      paths:
        - "calculator/"
    - component_id: "smiles"
      paths:
        - "smiles/"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
