codecov:
  token: 4064e915-0934-4671-86b0-4648b95be4e5
coverage:
  precision: 5
  range:
  - 0.0
  - 10.0
  round: up
coverage:
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: auto 
        threshold: 5
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
       # advanced settings
        branches: 
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
