codecov:
  token: 4064e915-0934-4671-86b0-4648b95be4e5
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: true
ignore:
  - "SwiftyAttributesTests"
coverage:
  precision: 2
  range: "70...99"
  round: up
  status:
    changes: true
    patch:
      default:
        target: 99
    project:
      default:
        target: 99
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: true
      method: true
  javascript:
    enable_partials: true
component_management:
  individual_components:
    - component_id: "github"
      paths:
        - ".github/"
    - component_id: "smiles"
      paths:
        - "smiles/"
    - component_id: "images"
      paths:
        - "images/"
        - "img/"
    - component_id: "repository"
      paths:
        - "pages/"
        - "repo-work/"
        - "static/"
        - "scripts/"
        - "root/"
        - "sarif/"
        - "logs/"
        - "provenance/"
        - ".adaconfig/"
        - ".botconfig/"
        - ".changeset/"
        - ".main files/"
    
comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
