FROM mcr.microsoft.com/dotnet/sdk:6.0-focal@sha256:525ce79a6f545131df515ce34f7ee086eb18e4d707eff9676b2678f2f23b6d9e AS dotnet

COPY . /src/
RUN mkdir -p /home/site/wwwroot
RUN cd /src/CompressImagesFunction && dotnet publish CompressImagesFunction.csproj -c Release --output /home/site/wwwroot

# Native Binaries
RUN cd /src/CompressImagesFunction && cp bin/Release/net6.0/runtimes/linux-x64/native/libgit2-b7bad55.so /home/site/wwwroot/bin/
RUN cd /src/CompressImagesFunction && cp bin/Release/net6.0/runtimes/linux-x64/native/Magick.Native-Q16-x64.dll.so /home/site/wwwroot/bin/

FROM mcr.microsoft.com/azure-functions/dotnet:4@sha256:612b4e43d96d2c84704cdef576e5e28fc27e1e13c8377e12db5935b50f641374

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
  curl libcurl4 autoconf automake libtool nasm make wget pkg-config

RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g svgo@^1.3.2

# Add support for mozjpeg
RUN cd /tmp && wget https://github.com/mozilla/mozjpeg/archive/v3.3.1.tar.gz
RUN cd /tmp && tar -xzf v3.3.1.tar.gz
RUN cd /tmp/mozjpeg-3.3.1 && autoreconf -fiv
RUN mkdir /tmp/mozjpeg-3.3.1/build
RUN cd /tmp/mozjpeg-3.3.1/build && sh ../configure && make install

RUN ln -s /opt/mozjpeg/bin/jpegtran /usr/local/bin/mozjpegtran
RUN ln -s /opt/mozjpeg/bin/cjpeg /usr/local/bin/mozcjpeg
