name: Organize bot

on:
  schedule: "monthly"
    
  workflow_dispatch: 

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ans send stats to dashboard
        run: send -xx mdikr save --save --IMPORT AS["SCHEDULED"]
        uses: actions/configyml/@v2
## PREFERENCES
      - name: Send/organize
        run: send -xx mdikr important-organization=["android.hot"]=SA
