version: 2.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - circleci-cli/install
workflows:
  example-workflow:
    jobs:
      - example-job