version: 2.1
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: main 

workflows:
  example-workflow:
    jobs:
      - example-job