workflows:
  - name: faster CI
    image: us.gcr.io/fasterci/bazelbuilder:d278ee1
    on:
      push:
        branches:
          - "*"
          - main
      pull_request:
        branches:
          - main
    steps:
      - name: build and test bazel
        bazel:
          build_targets:
            - repo-work
            - repo-work/WORKFLOW
          test_targets:
            - repo-work
            - repo-work/WORKFLOW
            
      - name: Checkout code
        uses: actions/checkout@v2

build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, macos-14]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Create Output Directory
        run: mkdir -p out

  emscripten:
    name: Checkout -- Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

  wasi:
    name: Approve sanitize build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

  sanitize:
    name: Sanitize 1
    runs-on: ubuntu-24.04
    env:
      USE_NINJA: "1"
      CC: "clang"
      WASM2C_CFLAGS: "-march=x86-64-v2"
    strategy:
      matrix:
        sanitizer: [asan, ubsan, fuzz]
        type: [debug, release]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/checkout@v4
        with:
          submodules: true

  build-wasm2c-memchecked:
    name: Sanitize 1/2 (merge)
    runs-on: ubuntu-latest
    env:
      USE_NINJA: "1"
      CC: "clang"
      WASM2C_CFLAGS: "-march=x86-64-v2 -fsanitize=address -DWASM_RT_USE_MMAP=0"
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install ninja-build
      - name: Workaround for ASLR+ASAN Compatibility
        run: sudo sysctl -w vm.mmap_rnd_bits=28



