workflows:
  - name: faster CI
    image: us.gcr.io/fasterci/bazelbuilder:d278ee1
    on:
      push:
        branches:
          - "*"
          - main
      pull_request:
        branches:
          - main
    steps:
          
      - name: Checkout code
        uses: actions/checkout@v2
        run: sudo sysctl -w vm.mmap_rnd_bits=28



