name: ImageBot
on:
  push:
    branches:
      - main
jobs:
  imagebot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ImageBot
        uses: imgbot/Imgbot@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          imagebotConfig: .imgbotconfig
