name: Pre-commit CI
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up pre-commit.ci
        uses: pre-commit/action@v2.0.0
        with:
          config: .pre-commit-config.yaml
