name: Stale to PR

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  stale-to-pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for stale issues
        uses: actions/stale@v9
        with:
          days-before-issue-stale: 1
          days-before-issue-close: 3
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale because it has not had recent activity."
          close-issue-message: "This issue has been closed due to inactivity."
