name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: false # optional (default = false)
        flags: unittests # optional
        name: codecov-umbrella # optional
        token: 4064e915-0934-4671-86b0-4648b95be4e5
        verbose: true # optional (default = false)

        # files: ./coverage1.xml,./coverage2.xml # optional
