loading the gif images

> loading...
> loading........
> ...
> ...
> ...
> ...
> ...
> 12% done...182/629 images loaded. Please wait...
> 49% done...
> ...
> ...
> 100% done. Please stand by...loading...
> loading completed!
